### ISSUE TITLE
Launchers not installing

### ISSUE THREAD

**Issue by Szymciacho** [moraroy/NonSteamLaunchers-On-Steam-Deck#161]
Hi,

Just tried to install EA App today, it seems to install, but after Steam restarts it's not in the library. It worked a few weeks ago. 

Is there an issue?

**Comment by moraroy** [comment]
@Szymciacho yeah I'm looking into it!

**Comment by moraroy** [comment]
@Szymciacho I'm closing this as this has been fixed with the new proton

**Comment by Szymciacho** [comment]
Doesn’t seem to be fixed for me. It still doesn’t install. There are two
lines in red in the log.



W dniu wt., 9.01.2024 o 23:23 Roy ***@***.***> napisał(a):

**Comment by moraroy** [comment]
@Szymciacho can you post your log? its in the downloads folder

**Comment by Szymciacho** [comment]
There you go


śr., 10 sty 2024 o 01:12 Roy ***@***.***> napisał(a):

**Comment by Szymciacho** [comment]
Did you get it? Sorry for bothering.

śr., 10 sty 2024 o 15:04 Szymon Cuchrowski ***@***.***>
napisał(a):

**Comment by Szymciacho** [comment]
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/13927803/NonSteamLaunchers-install.log)

**Comment by tanushshukla** [comment]
same issue for me too. same error in logs.
