### ISSUE TITLE
Issues with NSLGameScanner and Ubisoft Connect

### ISSUE THREAD

**Issue by sysmoon14** [moraroy/NonSteamLaunchers-On-Steam-Deck#169]
Hi, first of all - love this little app, makes life so much easier! Was very excited to see the addition of automatic game scanning.

That said, I'm running into some issues when using it, especially with the Ubisoft Connect launcher.

### 1. Not Finding Games
Initially I could not get the script to find any Ubisoft Connect games. I had a look at the script and found that in these two [line 466](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/blob/25b67e2879407b7abbf8df30a6ab1392ca773702/NSLGameScanner.py#L466) it is pointing to "{logged_in_home}/Desktop/compatdata" - if I change this to ""{logged_in_home}/.local/share/Steam/steamapps/compatdata" on both this line and the following line, then it begins to detect my games.

### 2. Game Names Not Matching
Now that I can get Ubisoft Connect games to scan, I'm on to my next problem (which I haven't been able to resolve). I have 3 games installed; Rayman Origins, UNO, and Prince of Persia: The Lost Crown. The only one that got added to steam after the tweak I made above was Rayman Origins.

I believe that this is because Rayman Origins is the only game in which the directory name exactly matches the entry on the GitHub list of Uplay IDs. See below:
- **Directory Name:** "Rayman Origins" **Github Entry:** "[Rayman Origins](https://github.com/Haoose/UPLAY_GAME_ID/blob/7248216e917f87a8f8858ae635070a16cc42f652/README.md?plain=1#L154)"
- **Directory Name:** "Prince of Persia The Lost Crown" **GitHub Entry:** "[Prince of Persia: The Lost Crown](https://github.com/Haoose/UPLAY_GAME_ID/blob/7248216e917f87a8f8858ae635070a16cc42f652/README.md?plain=1#L118)" - Note the colon in the github entry
- **Directory Name:** "UNO" **GitHub Entry:** "[UNO (Uplay)](https://github.com/Haoose/UPLAY_GAME_ID/blob/7248216e917f87a8f8858ae635070a16cc42f652/README.md?plain=1#L187)"

### 3. Duplicate Entries
I've also noticed that my two games that are scanning correctly (Rayman Origins from Ubi Connect and Cursed to Golf from Epic Games) are having duplicate entries created, which I've noticed upon restarting Steam multiple times. The duplicates do not have any artwork and don't have proton enabled, but are otherwise identical to the originally created shortcuts.

**Comment by moraroy** [comment]
@sysmoon14 Thanks for catching that I'm so dumb I left that path when I was testing lol my bad, I just fixed number 1 just i added the correct path to the script, but problems 1 and 2 may have to wait a bit maybe in a couple days I can try to fix the duplicates...just FYI it's not supposed to duplicate a short UT thats exactly the same meaning same exe, dir, launchoptions etc. Was that shortcut from somewhere like boilr or a manual shortcut?

**Comment by sysmoon14** [comment]
@moraroy great, thanks for sorting issue 1 out so quickly.

For issue 2 I actually just managed to get Prince of Persia to work by doing a replace on the string from GitHub and removing the colon, probably needs to be more robust than that though.

On the duplicated shortcuts, both the original and the duplicate were created by your script. I've even tried deleting all shortcuts and letting the script do it's thing again. Same result.

**Comment by sebastaub** [comment]
Hi @moraroy 

First, thank you for your amazing job !
I have the same trouble : the script duplicate my epic games every time a restart my steam deck or launch script. 
First shortcut created have artworks but all others have not (example with rocket league and art of really, now I have 5 shortcuts of each games ^^)

**Comment by moraroy** [comment]
@sysmoon14 @sysmoon14 and this only happening on the Epic Games shortcuts not ubisoft?

**Comment by sysmoon14** [comment]
It happened on both I believe but I can't confirm that for a day or two

**Comment by moraroy** [comment]
@sysmoon14 im unable to replicate the duplication for the games on my lcd deck...im thinking maybe it may have to do with how the service is handling things, im taking a look now

**Comment by sebastaub** [comment]
@moraroy the script doesn’t work with my Ubisoft games like @sysmoon14. 

I have an Oled deck, may be it’s specific to this model ?

**Comment by moraroy** [comment]
@sebastaub no I don't think it has to with the model.. not sure yet

**Comment by sysmoon14** [comment]
I'm actually struggling to reproduce the duplicate issue now. Wonder if it was an older version of the script? LCD model for what it's worth but I don't think it makes a difference.

**Comment by sysmoon14** [comment]
@moraroy 

I think I've found a better way of figuring out which Unisoft Connect games are installed. I looked at the Playnite code to see how they do it and it looks like they parse the registry, so I had a look and it seems that the system.reg file in the c drive of the compatdata includes a line per installed game, which includes the directory and the uplay ID. I'm on my phone ATM but if you don't beat me to it I might try to adapt your script to use this method.

If you look for "SOFTWARE\ubisoft\Launcher\Installs" in the system.reg file you'll see what I mean.

FYI this is the Playnite code that led me to it.

https://github.com/JosefNemec/PlayniteExtensions/blob/c33df30eed393305f9615423fd4385f3737d8d42/source/Libraries/UplayLibrary/UplayLibrary.cs#L92

**Comment by moraroy** [comment]
@sysmoon14 that's good news brother thank you, I already had half of that code before I released the scanner haha, I just couldn't find where the registry file was in proton, thank you! Feel free to do a pull a request if you manage to get it working correctly that would be a big help. I'll try to work on in it as well.

**Comment by moraroy** [comment]
@sysmoon14 I'm bout to update to fix this if that's OK with you!

**Comment by moraroy** [comment]
@sysmoon14 just updated, so now as soon as you start NonSteamLAunchers, the updated .py will be added into your system, for now in order to "start" the service you mayn need to make a selection like netflix or something or type in a website you want to quickly run the NonSteamLaunchers.sh, ill fix that a little later so the .py is able to do it on its own, but i seemed to have correctly parsed the Ubisoft Connect Games locally thanks to you pointing out the registry files! thank you, we may need to update it a little more in case some games have weird game names that have colons or hyphen or parenthesis. so we will see! let me know hows its working. still trying to figure out why there is duplication though!

**Comment by CASHatFOLSOM** [comment]
I'm getting duplicates as well, and tracked down this thread trying to figure out why.  I gotta say, adding an always-on service without any notification in the script or means to toggle the option off is kind of uncool.  I appreciate the hard work on this script but respectfully request a toggle for the scanner.

**Comment by moraroy** [comment]
@CASHatFOLSOM no worries brother I'm already working on the toggle thank you for using the script, sorry it isn't working as expected. I'm currently working on the best way to toggle the service in an automatic way that isn't intruding on people's system. Currently I'm just glad the correct games are being parsed and will have this fixed within the next couple hours.

**Comment by moraroy** [comment]
@CASHatFOLSOM are your duplicates for both ubisoft and epic? or just one or the other?

**Comment by CASHatFOLSOM** [comment]
Just Epic, but I don't have any Ubi games installed currently.

**Comment by CASHatFOLSOM** [comment]
Well, I installed a few Ubi games just to try and be helpful.  They also get duplicated.

**Comment by moraroy** [comment]
@CASHatFOLSOM tha k you for being brave... but to update in about 15 minutes. Thank you for letting me know that it's both! That's very helpful

**Comment by sysmoon14** [comment]
Ubi games are working nicely now! But when I updated the script my duplication issue returned, the only way to stop things from duplicating was to manually delete all shortcuts that NSLGameScanner had created, it then recreated them and stopped producing duplicates.

Hope that helps!

**Comment by moraroy** [comment]
@sysmoon14 @CASHatFOLSOM  i just updated the script one more time, hopefully this will complete the issue of duplication that has been happening im glad the ubisoft games are working brother <3, ive also added a new toggle button for scanner as well as a new message everytime you run the script so you know what is on and what isnt feel free to test it out!

**Comment by CASHatFOLSOM** [comment]
Well, I ran the new script, leaving the scanner on at first just to do some testing.  Unfortunately, it continued to produce duplicates every time Steam was restarted.  Luckily the toggle seems to work so I've turned the scanner off.

**Comment by moraroy** [comment]
@CASHatFOLSOM that's weird have you tried deleting them like @sysmoon14 has said?

**Comment by CASHatFOLSOM** [comment]
Yes, I even tried installing a fresh game to see how it behaves.  Same issue.  Honestly I'm still not really interested in an always-on service, so the toggle is enough for me.

**Comment by moraroy** [comment]
@CASHatFOLSOM I actually may have found out why I'm going to try to add one more fix, I fixed the duplication on the bash file just now, so I just updated now one more time. If not I'll keep researching and trying to figure out why maybe tomorrow.

**Comment by CASHatFOLSOM** [comment]
@moraroy one thing I hadn't tried is to see how the service would behave if I turned it on again after having it off for a bit.  I have determined that it will now only add a duplicate entry if I had previously moved the game to a collection.  e.g. if I move it from Uncategorized, to say, a collection named "Test" it will make a new duplicate in Uncategorized upon Steam restart.  As long as there is already an entry in Uncategorized it will now stop making duplicates in the way it would before, but obviously not being able to use categories is a pretty big issue.

Also I just saw your update so I'll do some more testing.

**Comment by sysmoon14** [comment]
I'm still seeing the duplication issue on the latest version, sorry! And I'm not organising my shortcuts into any collections either

**Comment by CASHatFOLSOM** [comment]
Yeah never mind, it's still intermittently creating additional duplicates even if I don't mess with collections (although moving a game to a collection is one consistent way to create a duplicate).  I just can't get this feature to behave reliably.  I might suggest making it opt-in for now, or removing it entirely until it can be made to work as expected.  Or another thought: just have it available to be run on demand via the script, rather than always listening.  Similar to Emudeck/Steam ROM Manager.

**Comment by moraroy** [comment]
@sysmoon14 wow :( OK I'll get back to the bottom of this...in the meantime the button is there to stop the service in case things break, good call on the toggle brother @CASHatFOLSOM

**Comment by moraroy** [comment]
Oh dang now I'm duplicating

**Comment by sysmoon14** [comment]
That's good! Hopefully means you can debug it now. I'm away from my main PC until Tuesday but if you haven't solved it by then I'll try to debug it my end

**Comment by sysmoon14** [comment]
I think I've partially figured out the duplication issue (not implemented a fix yet though).

Looking at my steam shortcuts vdf file, it seems that some field titles are inconsistent. For example some are AppID and some AppID, some are AppName and some are appname.

Here's what I think is happening - your script is creating the shortcut with AppName, for example, then at some point steam is sanitising the file and replacing it with appname. Then where your script looks for AppName it can't find it so it creates a new entry.

Will do more digging but that's my findings so far.

**Comment by moraroy** [comment]
@sysmoon14 thank you for the fix brother, ❤️ just merged it!! Let me know how everything is working! I never had the duplication problem on my end for some reason so I couldn't really test.

**Comment by sysmoon14** [comment]
Everything seems to be working well for me now. @CASHatFOLSOM can you check if you still get the duplicates please?

**Comment by piertobia** [comment]
Hi guys, is the Ubisoft Connect path fix avaible for download?

**Comment by CASHatFOLSOM** [comment]
Messed around with it last night, no duplicates were produced.  Of course the games I had already added to Steam myself (by directly adding their EXEs) were added again, but those new versions were not ever duplicated.  Sadly I forgot to transfer over the saves for those games from their old Steam IDs before removing them in favor of the new versions.  Ah well, they both had only a few hours invested so far.

Also the service doesn't seem to be smart enough to not add things like the Microsoft Visual C++ Redistributable that was required for one of my non-Steam games, so I created a "Non-Steam Hidden" collection for those entries that gets excluded from my Library in Tab Master, since I do intend to keep running the service, at least periodically.

Poking around the filesystem (originally trying to track down my saves before realizing I had unintentionally nuked them), I noticed some strangeness with symbolic links.  The game detector service points games to a "NonSteamLaunchers" link in Steam's compatdata folder, and that link points to the correct Steam ID in compatdata.  I suppose that makes sense given the fact that the Steam ID being used for non-Steam launchers is probably different for different users.  But also, that link was at some point added WITHIN the Steam ID for my non-Steam launchers--i.e. a link within a folder that pointed to the folder itself, recursively.  It seemed like an error so I removed it, and everything is still working fine.  I'm guessing if it was caused by the script, it was in a previous version, as the recursive link hasn't reappeared.

**Comment by sysmoon14** [comment]
> Hi guys, is the Ubisoft Connect path fix avaible for download?

It should be there in the latest build @piertobia

**Comment by moraroy** [comment]
@CASHatFOLSOM first off... the game scanner just scans your games.. it isn't downloading any extra things to make your games work. Each game is different and requires different things to make work. So yeah of course the scanner isn't smart enough. Secondly the sym links that are in compat data are for users that don't know anything about Linux, I put them there symlinked right next to each other so that when the lay man opens that folder...they see a folder labeled Nonsteamlaunchers as opposed to 123456789 if they are looking to mod or mess around in the prefix. That's why the symlink is there that's it.   It will still work if you delete the symlink. Same things happens if you selected "Separate App Id's" in the script. It was mostly for user friendly eyes to see where the launchers are.

**Comment by CASHatFOLSOM** [comment]
@moraroy oh yeah, I wasn't reporting the Visual Suite as a bug, just reporting my experience.  I'll go through my launchers and see if I can find one that installed it as a separate "game" just to satisfy my curiosity.  Maybe there's a future where a blacklist can be specified, but I'm fine with the behavior as is.  The symlink that was an error (now not reproducable with the current script) was IN the Steam ID folder for my non-Steam launchers (e.g  folder 123456789).  In other words, imagine somebody made a symlink to Documents in their Documents folder.  I left the one in compatdata.  Thanks for your work.

**Comment by moraroy** [comment]
@CASHatFOLSOM no worries brother I just wanted to clarify what was going on ❤️ I know the symlinks probably aren't the best way to do that but for now it's acceptable... in the near future I may have a better way in mind.

**Comment by CASHatFOLSOM** [comment]
For what it's worth, I like the symlinks!  I can never remember which random number I'm looking for so I was already using them in my setup anyway.

**Comment by piertobia** [comment]
> > Hi guys, is the Ubisoft Connect path fix avaible for download?
> 
> It should be there in the latest build @piertobia

at the moment I have installed prince of Persia via Ubisoft connect, on boilr I see a section dedicated to Uplay games but by downloading version 3.3 of nonsteamlauncher, when I do find games, it tells me that it has not found Uplay games

**Comment by moraroy** [comment]
@piertobia it finds it for you automatically just restart your deck

**Comment by piertobia** [comment]
@moraroy I download the latest release, 3.3, run it and click on Find Games, right? After that when I restart the deck I should find Prince of Persia in the steam library, is that correct? I have already tried a couple of times but so far it only finds Hades, which I have on EGS, Prince of Persia I don't even see it in the "non steam games" section. I'm playing PoP on Ubi+ monthly subscription, can it depend on this? Another doubt, the game is located in steamapps\compatdata etc, but in the drive_c folder I created a Games folder in which I put PoP and then manually imported it into Ubi Connect, having transferred the files to deck from PC, could this custom path have caused problems? Should I use the one set by default by Ubi Connect?
 
Thanks for your patience and sorry for the wall of text

**Comment by sysmoon14** [comment]
I think it's your custom path that's causing issues @piertobia . I've installed PoP natively using my deck (also Ubi+ subscriptions) and it was added to my non steam games no problem.

No need to click find games either, it does it automatically in the background

**Comment by piertobia** [comment]
@sysmoon14 Yeah, it was the path.  I fixed the path and now it adds it to the library.  However when I try to start PoP from the created shortcut I can't start it, it tries and then goes back to Steam.  However, opening it from Ubisoft Connect works

**Comment by CASHatFOLSOM** [comment]
@piertobia I did some testing with the demo previously, and found i needed to force Proton Experimental (or a recent GE Proton) to fix the behavior you are seeing.

**Comment by moraroy** [comment]
@sysmoon14 I think after the pull request merge the "force compatability" broke brother :(

**Comment by sysmoon14** [comment]
I'm seeing that too, but cannot figure out why!

**Comment by moraroy** [comment]
@sysmoon14 I think it may be an indentation problem

**Comment by sysmoon14** [comment]
I'm about to drop a pretty hefty pr which should fix it
