### ISSUE TITLE
Been downloading gog for 3 hours, no progress 

### ISSUE THREAD

**Issue by VRJacky** [moraroy/NonSteamLaunchers-On-Steam-Deck#417]
I love how because I decided to support Devs I'm punished and have to either pay for junk store or sit downloading with NSL for eternity, never using gog again

**Comment by moraroy** [comment]
@VRJacky well no one should wait 3 hours for something that should take less than 2 minutes ... also... you shouldn't have to pay any money either.... so, I'm going to assume... some things are broken. I would make sure you have the latest Proton GE installed first and then try to start fresh and then try to download and install gog again... also please upload your log in the Downloads folder.

**Comment by mtg92** [comment]
I had the same issue, uninstalling the latest proton GE and then reinstalling did the trick, GOG installed successfully after that.

**Comment by lechip** [comment]
I am facing this issue, reinstalled Proton GE 13 to no avail. It just gets stuck on the "Installing Game launchers" indefinitely

**Comment by ZohWeiss** [comment]
For anyone else coming here with this issue but no idea how to proceed based on the above suggestions:
In Desktop Mode, I used protonup-QT (https://davidotek.github.io/protonup-qt/) to uninstall Proton-GE 9.0-20 and reinstall it, then I went to the Downloads folder and deleted any GOG files in there. After doing that, GOG installed fine.

(Also of note, if you're using the on-screen keyboard to log in to GOG and you find yourself getting "Invalid Login" errors, don't hide the keyboard before hitting login, just hit the enter key instead.)

**Comment by jb098** [comment]
I'm having the same issue, even when following the steps to remove and reinstall proton and clean up any existing gog files. As far as I can tell from the log, the shell script is in some kind of loop where its constantly running pgrep for the GalaxySetup.tmp file. Seems to iterate forever until I back out

**Comment by moraroy** [comment]
@jb098 was this fixed in the latest update?

**Comment by mgrabowski84** [comment]
It's still happening for me. Fresh install. I've tried updating Proton, Fresh Start and reinstalling plugin.

Here is my log

[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/18697954/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@mgrabowski84 oh OK thanks... give me a sec

**Comment by moraroy** [comment]
@VRJacky @mtg92 @lechip @ZohWeiss @jb098 @mgrabowski84 ok si just added that same fix to the desktop version .let me know if it installs and doesnt get 'stuck". i believe this issue to be fixed and would like to close it.

**Comment by mgrabowski84** [comment]
@moraroy Hey, just wanted to let you know the fix is working. Great job, and thanks!
