### ISSUE TITLE
VKPlay - No system resource

### ISSUE THREAD

**Issue by rastorguevia** [moraroy/NonSteamLaunchers-On-Steam-Deck#526]
Good day to everyone. the launcher itself was installed and started without problems, downloaded the game, but when starting the game it does not see the exe. 
I understand it's because of the "broken path". 
Is it possible to fix this somehow?
![20241209_145940](https://github.com/user-attachments/assets/4b2c9dd1-3dde-4435-87ea-7baabeac7d5e)

**Comment by rastorguevia** [comment]
@moraroy I understand that this is most likely a very low-priority bug, but still, when can I expect a fix?

**Comment by rastorguevia** [comment]
thank you a lot

**Comment by rastorguevia** [comment]
Is there any progress?

**Comment by moraroy** [comment]
@rastorguevia when you download the game is there anything else in the game files? Like, did everything d own load or just that .exe?

**Comment by rastorguevia** [comment]
@moraroy All files are in place (as far as I can tell), everything has loaded, the game even passes the integrity check that is built into VkPlay, the problem arises precisely when starting the game from the Play button.

**Comment by rastorguevia** [comment]
Is there any progress? [2]

**Comment by moraroy** [comment]
@rastorguevia sorry this took so long, been busy since the holidays ... looking into it right now

**Comment by moraroy** [comment]
@rastorguevia this game isn't even available for me brother, it says it only plays in the cloud? Where do you live and how did you download it? I test other games as well they seem to be running and downloading fine.

**Comment by rastorguevia** [comment]
I live in the ru segment. I just checked the other games and they actually run. it seems that the problem is only with Lost Ark. I also checked the presence of the exe itself - it's there, but for some reason it doesn't want to run. sad. I will continue trying to launch it through something like port proton maybe. 
Anyway, thanks for trying.

**Comment by moraroy** [comment]
@rastorguevia added a scanner for your vk games!!  restart your scanner in desktop version

**Comment by moraroy** [comment]
@rastorguevia let me know how the VK Play scanner is working

**Comment by rastorguevia** [comment]
> added a scanner for your vk games!! restart your scanner in desktop version

is it in new upcoming version?
I rebooted nslgamescanner but it didn't help

**Comment by moraroy** [comment]
@rastorguevia what no way... I added to both desktop and the plugin, it should be working. What game did you try to add?

**Comment by moraroy** [comment]
@rastorguevia I added more fixes to the vk scanner just now be sure to update to the latest!

**Comment by rastorguevia** [comment]
> @rastorguevia I added more fixes to the vk scanner just now be sure to update to the latest!

in general, I installed everything from scratch, but it still doesn't work on the new version. I tried other games and came to the conclusion that only MMOs don't work. they transfer the login data directly to the exe (as far as I understand) and because of this they don't like something and there is an error with the "absence" of the exe file, although in fact it certainly exists

**Comment by moraroy** [comment]
@rastorguevia yeah it's been pretty difficult this vk play, I have an internal version I'm testing for the majority of games it seems to work now. I'll try to update the vkplay scanner again in a couple days.
