### ISSUE TITLE
Epic Games Launcher Installation Folder changed

### ISSUE THREAD

**Issue by racSF** [moraroy/NonSteamLaunchers-On-Steam-Deck#811]
Hi, today I tried your wonderful script for the first time, but it seems, that the installation of EGL does not work anymore.

Looking into the code, the following is the current state:

576:
epic_games_launcher_path1="${logged_in_home}/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe"
epic_games_launcher_path2="${logged_in_home}/.local/share/Steam/steamapps/compatdata/EpicGamesLauncher/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe"

When Installing it via your script, the folder is changed to the following atm:
"/home/deck/.local/share/Steam/steamapps/compatdata/EpicGamesLauncher/pfx/drive_c/Program Files/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.exe"

Since this is changed, the Shortcuts are not created, since the target is not valid anymore.

**Comment by Archibald20125** [comment]
yeah i think im having the same problem because epic games isnt showing up for me so likely the same thing

**Comment by TheHandsomeCoder** [comment]
I'll +1 that I updated to the latest (60 minor versions give or take) and now the epic games launcher is missing

**Comment by racSF** [comment]
I tried changing the mentioned lines, the Launcher is able to install, but scanning of games etc. does not work, too

**Comment by moraroy** [comment]
@racSF @Archibald20125 @Archibald20125 fixing as we speak , will let you know when

**Comment by racSF** [comment]
> [@racSF](https://github.com/racSF) [@Archibald20125](https://github.com/Archibald20125) [@Archibald20125](https://github.com/Archibald20125) fixing as we speak , will let you know when

Wonderful, hope that even the automatic scanning will provide new Library entries :)
Will you update the Decky Version, too or better stick to the desktop version ?

**Comment by Archibald20125** [comment]
> [@racSF](https://github.com/racSF) [@Archibald20125](https://github.com/Archibald20125) [@Archibald20125](https://github.com/Archibald20125) fixing as we speak , will let you know when

That’s great honestly the main reason I got nonsteamlaunchers was for epic I’m excited to see it working 😊

**Comment by moraroy** [comment]
@racSF @Archibald20125 @Archibald20125 fixed just now in both versions, I would uninstall epic specifically and then install it again, should give you the win64 versions for all shortcuts. Unfortunately will have to remake the shortcuts, sorry about that

**Comment by Archibald20125** [comment]
> [@racSF](https://github.com/racSF) [@Archibald20125](https://github.com/Archibald20125) [@Archibald20125](https://github.com/Archibald20125) fixed just now in both versions, I would uninstall epic specifically and then install it again, should give you the win64 versions for all shortcuts. Unfortunately will have to remake the shortcuts, sorry about that

sorry just checking so will it now work in the steam deck desktop

**Comment by moraroy** [comment]
@Archibald20125 it should yes

**Comment by Archibald20125** [comment]
> [@Archibald20125](https://github.com/Archibald20125) it should yes

ok sorry i know this is probably stupid but where is the download for the most resent version because previously i got it from releases but it was last updated 3 days ago sorry

**Comment by moraroy** [comment]
@Archibald20125 just released now, i was fixing duplication bug!

**Comment by Archibald20125** [comment]
> [@Archibald20125](https://github.com/Archibald20125) just released now, i was fixing duplication bug!

oh thats great thanks

**Comment by Archibald20125** [comment]
I dont know if its me but epic still isnt installing even when it said epic installed if it helps i have a steamdeck

**Comment by racSF** [comment]
> I dont know if its me but epic still isnt installing even when it said epic installed if it helps i have a steamdeck

I can also confirm this - I manually changed some files within the Deckyversion (since this one does not update automatically)
Things I did:

epic_scanner.py (Line 17++):
`item_dir = f"{logged_in_home}/.local/share/Steam/steamapps/compatdata/{epic_games_launcher}/pfx/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests/"
        dat_file_path = f"{logged_in_home}/.local/share/Steam/steamapps/compatdata/{epic_games_launcher}/pfx/drive_c/ProgramData/Epic/UnrealEngineLauncher/LauncherInstalled.dat"
        exe_template = f"\"{logged_in_home}/.local/share/Steam/steamapps/compatdata/{epic_games_launcher}/pfx/drive_c/Program Files/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.exe\""
        start_dir_template = f"\"{logged_in_home}/.local/share/Steam/steamapps/compatdata/{epic_games_launcher}/pfx/drive_c/Program Files/Epic Games/Launcher/Portal/Binaries/Win64/\""
        launch_options_template = f"STEAM_COMPAT_DATA_PATH=\"{logged_in_home}/.local/share/Steam/steamapps/compatdata/{epic_games_launcher}/\" %command% -'com.epicgames.launcher://apps/{{app_name}}?action=launch&silent=true'"`

NonSteamLaunchers.sh (Line 374++)
`epic_games_launcher_path1="${logged_in_home}/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.exe"
epic_games_launcher_path2="${logged_in_home}/.local/share/Steam/steamapps/compatdata/EpicGamesLauncher/pfx/drive_c/Program Files/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.exe"`

After Installing the Epic Launcher it is not marked as 'Installed' within NSL, so I started the Library-Item within Steam called "NonSteamLaunchers" - it opens a lightweigt Windows Explorer, where I was able to launch the Epic Updater - this created the necessary Files for NSL to work better.

Within this procedure I rebooted the deck several times, not sure on when exactly. I once ran the Desktop Version to force it to rescan the launchers.

Hope this helps ;)

**Comment by moraroy** [comment]
@racSF what do you mean by "this one does not update automatically" ?

**Comment by racSF** [comment]
> [@racSF](https://github.com/racSF) what do you mean by "this one does not update automatically" ?

Sure - when launching the Desktop Version of NSL via Desktop-Shortcut it launches the latest version from repository by curling the bash script. As far as I understand, the Decky-Plugin initially matches the version numbers, before updating any local files ;)

**Comment by moraroy** [comment]
@racSF in other words, you dont have the latest decky plugin version is what youre saying?

**Comment by racSF** [comment]
> [@racSF](https://github.com/racSF) in other words, you dont have the latest decky plugin version is what youre saying?

I have the latest version, but as @Archibald20125 mentioned, the installation of Epic still does not work - I updated to the latest version (Decky) and edited the local files (Decky) - since the version of the local files is the same as the latest in repo, it does not update and the changes are still working.

When trying to run the Desktop-Shortcut of NSL, the first thing it does, is downloading the repo-version, so I decided to do the changes on the Decky-Plugin, to test my assumptions:

1.) EGL has to be updated after Installation -> Run EpicUpdater.exe manually to populate UnrealEngine and ProgramData-Folders (NSL, better said the Scanner-Component, seems to need these to work correct)
2.) EpicGamesLauncher.exe Locations in NonSteamLaunchers.sh have to be corrected to -> drive_c/Program Files/Epic Games/Launcher/Portal/Binaries/Win64/EpicGamesLauncher.exe as mentioned above.
3.) (Decky) Corrected Folders, DAT and .exe Locations in epic_scanner.py after Line 17 as mentioned above

After these changes, the EGL is detected as installed and Games are automatically added to the Steam Library.

**Comment by moraroy** [comment]
@racSF why not uninstall epic and then install it again? Does that not work for you?

**Comment by pcvgs** [comment]
Yeah. I just installed Decky loader and nonsteam launcher today.  GoG installed fine but Epic games wont.  It says installed sucessfully but doesn't show up in non steam games.  GOG is there though.

Using a fresh install of Bazzite OS for Asus Rog Ally.

**Comment by racSF** [comment]
> [@racSF](https://github.com/racSF) why not uninstall epic and then install it again? Does that not work for you?

No, unfortunately it does not work - it always shows as not installed, so I decided to edit the Scripts with the mentioned changes - I am not sure, if this beahvior  applies, if the installation of Epic Games was done a while back, so try it yourself with a fresh installation ;)

**Comment by remoteman213** [comment]
Just confirming that it is still not working for a fresh install. I think the path needs to be adjusted as @racSF found. Epic Games now gets installed into "Program Files", but the script/scanner is looking for it in "Program Files (x86)"

**Comment by IoannesC** [comment]
Same problem, here. Epic Games launcher doesn't added to steam library. You can execute the launcher directly, but the Games are not added to Steam. Basically, Epic Games doesn't work now. 

Cachy OS on Lenovo Legion Go.

**Comment by SanktyRG** [comment]
Hello, same exact issue here. No shortcut for Epic Games Launcher after installation. Also games installed also don't get added nor manually nor automatically to Steam.

I'm on a Steam Deck.

**Comment by moraroy** [comment]
Ok, a pull request was made to fix the initial  path correction as all of you explained was the issue, thank you. However I wanted to make sure the scanner was also working so I made the same adjustments there as well. Please confirm that the .desktop file will correctly find the correct launcher and games.

**Comment by SanktyRG** [comment]
> Ok, a pull request was made to fix the initial path correction as all of you explained was the issue, thank you. However I wanted to make sure the scanner was also working so I made the same adjustments there as well. Please confirm that the .desktop file will correctly find the correct launcher and games.

The storefront and its Steam shortcut install correctly using this version of the Desktop App. Games installed now show correctly on Steam but I seem to have two shortcuts for some games.

Could this changes be implemented to the Decky Plugin too? Thank you!

Also, Game Jolt seems to be having a similar issue with its storefront installation.

**Comment by moraroy** [comment]
@felixsrg yeah delete the old shortcuts, ganejolt doesnt install because there is no stable url to use as they are all time restricted

**Comment by moraroy** [comment]
this issue may be a problem so im pinning it

**Comment by kuynh** [comment]
Can confirm that plugin version of NSL can't install epic games but every other launcher does work. Desktop version does install epic games successfully, but I am willing to wait for the plugin version.

**Comment by IoannesC** [comment]
Now, the desktop version works correctly (Installing and adding Epic Games Launcher and...adding Epic Games entries). And yep, the plugin version with problems (Adding Epic Games with plugin but...bad. Every game added in this way shows a message ingame "Incorrect route" and an OK button, then closes. 

Thanks for this incredíble work.

**Comment by moraroy** [comment]
@IoannesC @kuynh fixed just now in the decky plugin I believe, please test to confirm

**Comment by kuynh** [comment]
> [@IoannesC](https://github.com/IoannesC) [@kuynh](https://github.com/kuynh) fixed just now in the decky plugin I believe, please test to confirm

Thanks, is there a new release that I need to download or will the plugin just work now?

Edit: Just tried to run the plugin with epic games installation with no success.

**Comment by IoannesC** [comment]
@kuynh I updated the plugin from the .desktop file and now, for me, the addition of epic Games works perfect. I dont know If the installation of Epic Launcher works (Mine is installed and added in Steam and you know...don't touch something that works xD). 

-o-


So...the desktop app works perfectly right now (I installed the epic Games launcher with that). 
And the plugin works, almost, to add the Games (with no duplicated shortcuts in steam, so thats great). 

Someone to proof the epic Games launcher installation from the plugin. Consider that the plugin update from decky is bugged (Never update)...You need to update from .desktop file in desktop mode. 

And thanks again for this amazing thing.

**Comment by moraroy** [comment]
@IoannesC the decky plugin bug of "not updating" should be fixed with the latest version too

**Comment by kuynh** [comment]
Thank you @moraroy, the update to the plugin worked. I was able to install epic games and get some games up and running. 
Thanks your work.

**Comment by leadenmoth** [comment]
Still can't install Epic with desktop version 4.2.74 (steam deck). After "successful" install files appear in the prefix in Program Files (x86) and ProgramData, but no shortcut appears in steam. On subsequent runs of NSL, Epic is listed without a path - i.e. the scanner didn't notice it. If I check it and uninstall, the dialog actually says it's downloading and installing it (same result).
My starting point was an older desktop version with already installed Epic. NSL prompted me to update, and the new version didn't see Epic and I think removed it from steam (?)

**Edit:** now that I think about it and look through recent commits, my problem seems to be the exact opposite of this issue - the launcher downloads and installs in **x86** and the updated version doesn't see it

**Edit2:** could it be that because NSL no longer sees the x86 installation, it can't cleanly uninstall it, and the installer defaults to some sort of update mode based on the prefix's "registry"? (Simply deleting the folders in x86 and ProgramData doesn't help)

**Comment by leadenmoth** [comment]
I can work around the uninstallation failure by downloading NonSteamLaunchers.sh from before the fix and running from command line with "Uninstall Epic Games", but this doesn't undo whatever is causing the new version to keep installing to  x86 for me (also, the ProgramData/Epic and AppSettings/Local/Epic are not removed by the uninstaller routine, but deleting them manually after running uninstall also doesn't solve the issue)

**Edit:** there was also an msi package in one of the folders in ProgramData/Package Cache/ but deleting it also doesn't help. Also Proton apparently creates an Epic Games Launcher.desktop file under drive_c/proton_shortcuts, and it's pointing at the de-facto path in x86
**Edit2:** ironically, i can install epic with the old shell script via command line, and it works, but the new NSL desktop will delete it when launched

Another theory (aside from wine/proton having an equivalent of windows registry where the old path might be stuck) is that maybe the different folders are some sort of A/B test on Epic's side?

**Comment by patryksliwinski** [comment]
Hello I'm unsure if my issue is exactly the same, but when I install epic games store, the shortcut is not added in steam therefore i cannot use epic games, i'm using latest 4.2.75

**Comment by moraroy** [comment]
@patryksliwinski can you upload your log?

**Comment by patryksliwinski** [comment]
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/24260956/NonSteamLaunchers-install.log)

**Comment by patryksliwinski** [comment]
Is there a chance to have epic games installation fixed? Still doesn't work for me

Edit: update from my side after running "start fresh" and installing all launchers again the epic games started to appear in steam and now it works 🥳,  though not a nice way for people who have other games installed

**Comment by moraroy** [comment]
@patryksliwinski not sure why it was being detected in the first place. A small number of people seemed to have that issue, but code wise I couldn't find anything just yet. Im glad its working now though for you.

**Comment by mephistofoles** [comment]
Hopefully the following will help others like me who read through this entire thread and tried everything (other than the nuclear option of "start fresh").

I noticed that Epic was installed in the "Program Files x86" folder and there was an empty Epic Games folder in "Program Files" so I simply copied all files from x86 Epic folder to Program Files Epic folder.

After doing this I reran the desktop NSL launcher and it detected Epic and added the shortcut to Steam. I needed to reinstall all my Epic Games as they were missing from the x86 folder (perhaps due to the uninstall Epic step I attempted), but once I did that everything was working correctly and NSL was able to restore my save files for all but one of my Epic games. I simply had to remove the old shortcuts from steam and I was back in business!

Thank you @moraroy for all your hard work on this. We truly appreciate it!
