### ISSUE TITLE
Script not working for Gog Galaxy, Epic Game Store and Ubisoft Play

### ISSUE THREAD

**Issue by bukson** [moraroy/NonSteamLaunchers-On-Steam-Deck#97]
Hello

I've done everything presented as instruction, running script for installing Gog Galaxy, Epic Game Store and Ubisoft Play and Battle net. The only thing that seems to work is Battle net, it only launches out of those 4 to provide some input for login. Other stores are not working. Changing compatibility to Proton Experimental does nothing. Unfortunately I cant provide much more information, because when I click "play" in steam, either in desktop or in normal mode, it is just try to run it and then again button turns green without any output.

I am on stable steamdeck branch. 

Please if you need more information I can provide it but it does not seem obvious where to get it.

Fresh install does not work either

Regards

**Comment by jwehrli** [comment]
I had the same issue, what worked for me was restarting my deck and launching the apps through game mode instead of the desktop. Hope this helps!

**Comment by moraroy** [comment]
@bukson @jwehrli theres a been alot of updates to the .sh file let me know if this issue has since been fixed i just pushed an update to the .sh file

**Comment by mrmldeboy** [comment]
same issues, all launchers broken after v2.99. All were working properly under v2.96

**Comment by poltpolt** [comment]
I have the same issue with the latest version seams like it is stuck in
```
    # Cancel & Exit the GOG Galaxy Setup Wizard
    while true; do
        if pgrep -f "GalaxySetup.tmp" > /dev/null; then
            pkill -f "GalaxySetup.tmp"
            break
        fi
        sleep 1
    done
```

I tried to troubleshoot, found that $STEAM_RUNTIME" "$proton_dir/proton" run "$exe_file still shows the protondir from steam. 
I dowloaded another wine with proton-QT and chose this wine to install he $exe_file and it started it fine

**Comment by BryanFish** [comment]
Tried today with version 3.00 GOG was mapped into steam automatically manually mapped it from NonSteamLaunchers folder and it still won't run
